Adding slurm calls that should work inside container.

diff --git a/SAMBA_startup b/SAMBA_startup
--- a/SAMBA_startup
+++ b/SAMBA_startup
@@ -1,9 +1,7 @@
 #!/bin/bash
 # SAMBA startup script for running the main pipeline as a cluster job.
 
-# -------------------------
-# Locate SAMBA root (SPath)
-# -------------------------
+# Resolve SAMBA path
 if [[ -d "${SAMBA_PATH}" ]]; then
     SPath="${SAMBA_PATH}"
 elif [[ -d "${SAMBA_APPS_DIR}/SAMBA" ]]; then
@@ -12,68 +10,48 @@ else
     SPath="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
 fi
 
-# -------------------------
-# Perl environment
-# -------------------------
+# Perl local lib
 local_perl="${SPath}/local/lib/perl5"
 PERL5LIB="${local_perl}"
 export PERL5LIB
 
-# -------------------------
-# Decide how to launch pipeline
-#   - If CONTAINER_CMD_PREFIX is set (from samba-pipe),
-#     we *wrap* the vbm_pipeline_start.pl call so that:
-#       - direct (no-cluster) runs are in the container
-#       - sbatch/qsub scripts also run inside the container
-#   - Otherwise we just run the perl script directly.
-# -------------------------
+##############################################################################
+# Decide how to launch the pipeline
+#
+# If CONTAINER_CMD_PREFIX is set (from samba-pipe), we use it to wrap
+# vbm_pipeline_start.pl so that *every* subsequent sbatch/qsub job also
+# runs inside the container.
+##############################################################################
+
 if [[ -n "${CONTAINER_CMD_PREFIX:-}" ]]; then
     PIPELINE_LAUNCH="${CONTAINER_CMD_PREFIX} ${SPath}/vbm_pipeline_start.pl"
 else
     PIPELINE_LAUNCH="${SPath}/vbm_pipeline_start.pl"
 fi
+export PIPELINE_LAUNCH
 
-# Debug: show what we are about to run from this process
+# Optional debug
+if [[ "${SAMBA_DEBUG:-0}" != "0" ]]; then
+    echo "[SAMBA_startup] SPath=${SPath}" >&2
+    echo "[SAMBA_startup] CONTAINER_CMD_PREFIX=${CONTAINER_CMD_PREFIX:-<unset>}" >&2
+    echo "[SAMBA_startup] PIPELINE_LAUNCH=${PIPELINE_LAUNCH}" >&2
+    echo "[SAMBA_startup] ARGS: $@" >&2
+fi
+
 echo "${PIPELINE_LAUNCH} $@"
 echo " "
 echo " "
 
-# -------------------------
 # Detect cluster type
-#   cluster_code = 0 : no cluster
-#   cluster_code = 1 : Slurm
-#   cluster_code = 2 : SGE
-# -------------------------
-cluster_code="$(bash "${SPath}/cluster_test.bash")"
-
-# Normalize / sanity
-if [[ -z "${cluster_code}" ]]; then
-    cluster_code=0
-fi
+cluster_code=$(bash "${SPath}/cluster_test.bash")
 
 if ((! cluster_code)); then
-    # ---------------------------------------------
-    # No cluster: run pipeline directly via launcher
-    # ---------------------------------------------
-    # Build a safely quoted command line for eval
-    qargs=()
-    for a in "$@"; do
-        qargs+=( "$(printf '%q' "$a")" )
-    done
-
-    cmd="${PIPELINE_LAUNCH}"
-    for qa in "${qargs[@]}"; do
-        cmd+=" ${qa}"
-    done
-
-    eval "${cmd}"
+    # No cluster: run directly (still via container if PIPELINE_LAUNCH uses it)
+    eval "${PIPELINE_LAUNCH} $@"
 else
-    # ---------------------------------------------
-    # Cluster case (Slurm or SGE)
-    # ---------------------------------------------
 
-    # Notification email
-    if [[ -z "${NOTIFICATION_EMAIL:-}" ]]; then
+    ## It is recommended to setup NOTIFICATION_EMAIL in env, bashrc, or bashrc_for_SAMBA
+    if [[ "x${NOTIFICATION_EMAIL}x" == "xx" ]]; then
         email="${USER}@duke.edu"
     else
         email="${NOTIFICATION_EMAIL}"
@@ -85,83 +63,77 @@ else
         mkdir -m 775 "${sb_dir}"
     fi
 
-    date_tag="$(date --rfc-3339=seconds | tr ' ' '_' | tr ':' '.' | tr -d '-')"
+    date_tag=$(date --rfc-3339=seconds | tr ' ' '_' | tr ':' '.' | tr -d '-')
     name="SAMBA_pipeline_${date_tag}"
     sbatch_file="${sb_dir}/${name}.bash"
     outfix="${sb_dir}/slurm-"
 
-    # -----------------------------
-    # Write scheduler script
-    # -----------------------------
-    {
-        echo '#! /bin/env bash'
+    echo '#! /bin/env bash' > "${sbatch_file}"
 
-        if [[ "${cluster_code}" == 1 ]]; then
-            # ----- Slurm -----
-            echo '#SBATCH  --mem=8000'
-            echo '#SBATCH  -v'
-            echo '#SBATCH  -s'
-            echo "#SBATCH --mail-user=${email}"
-            echo '#SBATCH --mail-type=END,FAIL'
-            echo "#SBATCH --output=${outfix}%j.out"
-            echo "#SBATCH --error=${outfix}%j.out"
-            echo "#SBATCH --job-name=${name}"
-
-            # IMPORTANT: use PIPELINE_LAUNCH so jobs run in container when available
-            echo "${PIPELINE_LAUNCH} $@"
-
-        elif [[ "${cluster_code}" == 2 ]]; then
-            # ----- SGE -----
-            echo "#\$ -N ${name}"
-            echo "#\$ -M ${email}"
-            echo '#\$ -m ea'
-            echo "#\$ -o ${outfix}"'$JOB_ID.out'
-            echo "#\$ -e ${outfix}"'$JOB_ID.out'
-            echo '#\$ -l h_vmem=8000M,vf=8000M'
-
-            # Same here: use PIPELINE_LAUNCH
-            echo "${PIPELINE_LAUNCH} $@"
-        fi
-    } > "${sbatch_file}"
-
-    # -----------------------------
-    # Submit to scheduler
-    # -----------------------------
-    if [[ "${cluster_code}" == 1 ]]; then
+    if [[ ${cluster_code} == 1 ]]; then
+        ######################################################################
         # Slurm
+        ######################################################################
+        echo "#SBATCH  --mem=8000"                    >> "${sbatch_file}"
+        echo "#SBATCH  -v"                            >> "${sbatch_file}"
+        echo "#SBATCH  -s"                            >> "${sbatch_file}"
+        echo "#SBATCH --mail-user=${email}"           >> "${sbatch_file}"
+        echo "#SBATCH --mail-type=END,FAIL"           >> "${sbatch_file}"
+        echo "#SBATCH --output=${outfix}%j.out"       >> "${sbatch_file}"
+        echo "#SBATCH --error=${outfix}%j.out"        >> "${sbatch_file}"
+        echo "#SBATCH --job-name=${name}"             >> "${sbatch_file}"
+
+        # *** CRITICAL: use PIPELINE_LAUNCH so sbatch runs via container ***
+        echo "${PIPELINE_LAUNCH} $@"                  >> "${sbatch_file}"
+
         cmd="sbatch ${sbatch_file}"
+
         echo "${cmd}"
         echo " "
         echo " "
-        job_id="$(${cmd} | awk '{print $4}')"
+
+        job_id=$(${cmd} | cut -d ' ' -f 4)
         kill_cmd="scancel ${job_id}"
 
-    elif [[ "${cluster_code}" == 2 ]]; then
+    elif [[ ${cluster_code} == 2 ]]; then
+        ######################################################################
         # SGE
+        ######################################################################
+        echo "#\$ -N ${name}"                         >> "${sbatch_file}"
+        echo "#\$ -M ${USER}@duke.edu"               >> "${sbatch_file}"
+        echo "#\$ -m ea"                             >> "${sbatch_file}"
+        echo "#\$ -o ${outfix}"'$JOB_ID.out'         >> "${sbatch_file}"
+        echo "#\$ -e ${outfix}"'$JOB_ID.out'         >> "${sbatch_file}"
+        echo "#\$ -l h_vmem=8000M,vf=8000M"          >> "${sbatch_file}"
+
+        # Again, use PIPELINE_LAUNCH here
+        echo "${PIPELINE_LAUNCH} $@"                 >> "${sbatch_file}"
+
+        # 9 January 2020 (Thurs): '-b y' was not the right thing to do here.
+        # 27 February 2020 BJA: For BIAC cluster, want to run on long queue.
         q_string=''
         host="${HOSTNAME}"
-        host_test="$(echo "${host}" | sed 's/blade[0-9]*.dhe.duke.edu//g')"
+        host_test=$(echo "${host}" | sed 's/blade[0-9]*.dhe.duke.edu//g')
         if [[ "x${host_test}x" == "xx" ]]; then
             q_string="-q long.q "
         fi
+
         cmd="qsub ${q_string}-terse -V ${sbatch_file}"
         echo "${cmd}"
         echo " "
         echo " "
-        job_id="$(${cmd} | tail -1)"
+
+        job_id=$(${cmd} | tail -1)
         kill_cmd="qdel ${job_id}"
     fi
 
     echo "JOB ID = ${job_id}"
     echo ""
 
-    # -----------------------------
-    # Kill command hint / clipboard
-    # -----------------------------
-    pb_test="$(which pbcopy 2>&1 | grep 'no pbcopy in' | wc -l)"
-    if [[ "x${pb_test}x" == "x0x" ]]; then
+    pb_test=$(which pbcopy 2>&1 | grep 'no pbcopy in' | wc -l)
+    if [[ "x${pb_test}x" == 'x0x' ]]; then
         echo "To stop this instance of SAMBA pipeline please use the following command, and will be automatically copied to your clipboard :"
-        printf '%s\n' "${kill_cmd}" | pbcopy
+        pbcopy < <(printf '%s\n' "${kill_cmd}")
     else
         echo "To stop this instance of SAMBA pipeline please use the following command:"
         echo "${kill_cmd}"
@@ -170,7 +142,8 @@ else
     sleep 3
 
     sb_file="${sb_dir}/slurm-${job_id}.out"
-    touch "${sb_file}"   # ensure existence
+    # Make sure it exists so tail -f doesn't error out
+    touch "${sb_file}"
     tail -f "${sb_file}"
 fi
 
